spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    driver-class-name: 	org.postgresql.Driver
    username: postgresql
    password: postgresql
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: create
task-executor:
  max-pool-size: 3